### ISSUE TITLE
Usage of PackageVersions\Versions is deprecated

### ISSUE THREAD

**Issue by giorgiosironi** [elifesciences/api-sdk-php#262]
https://github.com/elifesciences/api-sdk-php/blob/04301024471139499313520a6907369937bae67d/src/ApiSdk.php#L160 is detected as deprecated when the `journal` PHPUnit tests are run:
```
Remaining indirect deprecation triggered by test\eLife\Journal\ViewModel\Converter\AnnotationAnnotationTeaserConverterTest::samples:
getRawData only returns the first dataset loaded, which may not be what you expect. Use getAllRawData() instead which returns all datasets for all autoloaders present in the process.
Stack trace:
#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(16384, 'getRawData only...', '/srv/journal/ve...', 262, Array)
#1 vendor/composer/InstalledVersions.php(262): trigger_error('getRawData only...', 16384)
#2 vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(57): Composer\InstalledVersions::getRawData()
#3 vendor/elife/api-sdk/src/ApiSdk.php(160): PackageVersions\Versions::getVersion('elife/api-sdk')
#4 test/ViewModel/Converter/SerializerAwareTestCase.php(19): eLife\ApiSdk\ApiSdk->__construct(Object(Mock_HttpClient_eccaaddc))
#5 test/ViewModel/Converter/ModelConverterTestCase.php(76): test\eLife\Journal\ViewModel\Converter\ModelConverterTestCase->setUpSerializer()
```

This causes a wall of warnings that hides the test results:
```
  205x: getRawData only returns the first dataset loaded, which may not be what you expect. Use getAllRawData() instead which returns all datasets for all autoloaders present in the process.
    10x in HomeControllerTest::it_displays_different_types_in_hero_banner from test\eLife\Journal\Controller
    10x in HomeControllerTest::it_displays_different_types_in_highlight_item from test\eLife\Journal\Controller
    8x in HomeControllerTest::it_displays_a_404_when_not_on_a_valid_page from test\eLife\Journal\Controller
    4x in HomeControllerTest::it_displays_the_homepage from test\eLife\Journal\Controller
    3x in HomeControllerTest::it_has_a_view_selector_when_secondary_column_introduced from test\eLife\Journal\Controller
    3x in HomeControllerTest::it_displays_the_homepage_even_if_the_api_is_unavailable from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_has_the_header from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_may_have_a_call_to_action from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_has_the_sign_up_cta from test\eLife\Journal\Controller
    2x in HomeControllerTest::subjects_are_rewritten from test\eLife\Journal\Controller
    2x in AnnotationAnnotationTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    2x in HomeControllerTest::it_has_the_footer from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_configures_javascript_libraries_through_a_script_element from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_has_metadata from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_displays_reviewed_preprint_on_homepage_listing from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_displays_the_correct_article_status_and_article_type_and_article_date_in_the_latest_research_listing from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_has_announcements from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_displays_a_subjects_list from test\eLife\Journal\Controller
    2x in HomeControllerTest::it_has_global_metadata from test\eLife\Journal\Controller
    1x in FigureAssetImageConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in PersonProfileSnippetConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in BookReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in BookChapterReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in PromotionalCollectionContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ProfileContentHeaderProfileConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PressPackageTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PressPackageContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeMediaChapterListingItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeGridTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeChapterRelatedItemTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeChapterReadMoreItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PodcastEpisodeAudioPlayerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PersonAuthorDetailsConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ConferenceProceedingReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in JobAdvertContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightPressPackageSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ImagePictureConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in InterviewContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in InterviewSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in InterviewSocialMediaSharersConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in InterviewTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in JobAdvertSocialMediaSharersConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in PersonAboutProfileConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in JobAdvertTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in LabsPostContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in LabsPostGridTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in LabsPostSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in LabsPostTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in MediaContactParagraphConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ClinicalTrialReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in DataReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in HighlightPodcastEpisodeChapterSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleReadMoreItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in BoxConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in AssetFileAdditionalAssetConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleRelatedItemTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleModalConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CodeConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ArticleMetaConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleDownloadLinksListConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleDecisionLetterHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ArticleAuthorsConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in AnnualReportTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ButtonConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ExcerptConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in JournalReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in UnknownReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in PatentReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in PeriodicalReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in PreprintReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in ReportReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in SoftwareReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in ThesisReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in WebReferenceConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Reference
    1x in SubjectContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ReviewedPreprintReadMoreItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ReviewedPreprintRelatedItemTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ReviewedPreprintSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ReviewedPreprintTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ReviewerProfileSnippetConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in SubjectBlockLinkConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightPodcastEpisodeSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightLabsPostSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in FigureAssetTableConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in BlogArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverBlogArticleHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverBlogArticleHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverBlockLinkConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverArticleHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverArticleHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ContentAsideConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CollectionTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CollectionSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CollectionRelatedItemTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CollectionReadMoreItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CollectionContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in BlogArticleTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in BlogArticleSocialMediaSharersConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in BlogArticleContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverCollectionHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ParagraphConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in FigureAssetVideoConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in FigureConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in GoogleMapConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ImageConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ListingConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in MathConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ProfileConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in YouTubeConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in QuestionConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in QuoteConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in SectionConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in TableConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in TweetConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in VideoConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in CoverBlogArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverCollectionHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightInterviewSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in ExternalArticleReadMoreItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DigestSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DigestSocialMediaSharersConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DigestTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in EventContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in EventSocialMediaSharersConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in FigshareConverterTest::samples from test\eLife\Journal\ViewModel\Converter\Block
    1x in ExternalArticleRelatedItemTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DigestContentHeaderConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in GroupAuthorDetailsConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightBlogArticleSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightCollectionSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightDigestSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in HighlightEventSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DigestGridTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in DataSetConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverCollectionSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPodcastEpisodeHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverEventHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverEventHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverEventSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverInterviewHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverInterviewHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverInterviewSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPodcastEpisodeHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverReviewedPreprintSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPodcastEpisodeSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPressPackageHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPressPackageHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverPressPackageSecondaryTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverReviewedPreprintHeroBannerConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in CoverReviewedPreprintHighlightItemConverterTest::samples from test\eLife\Journal\ViewModel\Converter
    1x in EventTeaserConverterTest::samples from test\eLife\Journal\ViewModel\Converter
```

**Comment by giorgiosironi** [comment]
https://github.com/composer/package-versions-deprecated suggests on Composer 2 the [Composer\InstalledVersions](https://getcomposer.org/doc/07-runtime.md#installed-versions) class can be used instead.

**Comment by giorgiosironi** [comment]
I tried to use `Composer\InstalledVersions` and it came up with a 7-day old commit when calling `getReference()`. Cannot find where calls to `getVersion()` are issued, if they still are.

**Comment by giorgiosironi** [comment]
Somehow the `User-Agent` of journal requests is
```
User-Agent: eLifeJournal/dev-develop@d9f550b eLifeApiSdk/dev-master@0fca8b4 eLifeApiClient/v1.1.0 GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.1.33
```
which with multiple commits per hour is useless information.
